server:
 port: 9999

spring:
#  datasource:
#   url: jdbc:mysql://localhost:3306/employee_directory
#   username: springstudent
#   password: springstudent
#  jpa:
#   hibernate:
#    ddl-auto: update
#  show-sql: true

  profiles:
   active: prod

  security:
    oauth2:
     client:
       registration:
          github:
            clientId: 913dfd5a038329b833c2
            clientSecret: 03f13495bd4202db6a6ade32b7c124c5c2bc7b58

          google:
            clientId: 1092876035459-fe9kt35svmdf6og1tjvsrb2rsk09bb0e.apps.googleusercontent.com
            clientSecret: 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
  
logging:
  level:
    org:
      springframework:
        security: TRACE


