spring:
  datasource:
    url: jdbc:mysql://containers-us-west-135.railway.app:5803/railway
    username: root
    password: oelu1rB74UOv80UFK6SP
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true